#!/usr/bin/env Rscript
library("optparse")
library(tximport)

option_list <- list(
  make_option(c("--indir"), type = "character", default = NULL, 
              help = "dir of the transcript quant file generated by Salmon", metavar = "character"),
  make_option(c("--tx2gene_map"), type = "character", default = NULL, 
              help = "a two-column map file to show correspondence between transcript id and gene id", metavar = "character"),
  make_option(c("--output"), type = "character", default = NULL, 
              help = "path to the gene-level quant file", metavar = "character")
); 


opt_parser <- OptionParser(option_list = option_list)
opt <- parse_args(opt_parser)

tx2gene_map <- read.table(opt$tx2gene_map, header = TRUE, sep = "\t")

# ============================================================================ #
# output summary quant table

samples <- list.files(path = opt$indir, full.names = TRUE, pattern="transcripts_quant$")
files <- file.path(samples, "quant.sf")

tmp_name1 <- sub(paste0(opt$indir, "/"), "", samples) 
tmp_name2 <- sub(".transcripts_quant", "", tmp_name1)
names(files) <- tmp_name2

txi <- tximport(files, type = "salmon", tx2gene = tx2gene_map[,c("transcript_id", "gene_id")], countsFromAbundance = "lengthScaledTPM")
df_counts <- round(data.frame(txi$counts, row.names = NULL))
output_data <- data.frame(gene_id = rownames(txi$counts), df_counts)
write.table(output_data, file = opt$output, sep = "\t", quote = FALSE, row.names = FALSE)

